name: green_env
dependencies:
  - python=3.10
  - matplotlib
  - seaborn
  - numpy
  - scikit-learn
  - pip
  - pip:
      - keras==3.6
      - tensorflow==2.18
      - opencv-python
 

# conda env create -f environment.yml

